### ISSUE TITLE
Using `rg` but still seeing Git ignored files, searches taking a long time

### ISSUE THREAD

**Issue by nrser** [antelle/atom-codesearch#1]
Hey, first off, thanks for putting this package together, I've got a lot of "composite" projects with multiple submodules, vendor'd libraries and cache/build files... basically, a decent amount of files (tens of thousands).

I was looking for a solution using RipGrep (`rg`) because it respects `.gitignore` and is blazing fast. When I'm searching in the editor I almost always am looking for checked-in code (for obvious reasons), and it works perfect from the command line.

However, when using it as the backend to codesearch (it says "Find in Project with `rg`" above the search form, not sure how else to check that's what it's really using) I'm getting results from directories with are ignored in Git, and it's taking way, way longer than running `rg` from the command line... like under `100ms` from the CLI and several seconds in Atom/codesearch.

Maybe the slowness is *because* it's searching all sorts of ignored files?

Regardless, I don't want to search ignored files and directories - which is the default behavior of `rg`. I'm have to assume that `rg` is getting told not to respect `.gitgnore` files at some point? Any idea what is happening or what I can do to fix it?

I can't turn on the "Exclude VCS Ignored Patterns" in Atom's *Core Settings* because it *removes those files from the tree-view* I need to be able to see, open and edit them - projects with complex build behavior create a ton of *really* important files that are not checked in, and I need to look at them and sometimes edit them - but I almost never want to wait to search them or see their results.

Thanks in advance, Neil.

**Comment by antelle** [comment]
Hi, just as a quick status update - I'm not actively maintaining this project because I'm not using Atom for now.
Things that can help:
- enable debug mode in settings and see what gets executed
- you can also add additional command line arguments in settings

So, feel free to look into it and contribute, it will be merged of course.

**Comment by nrser** [comment]
Cool, I understand, thanks for the response. I'll muck around with it if I manage to find the time.
