### ISSUE TITLE
This doesn't seem to work anymore

### ISSUE THREAD

**Issue by lacostenycoder** [antelle/atom-codesearch#3]
I have `ag` installed and it works like lightning in the terminal, but searches in atom seem to create indexes on the fly on the first search of a keyword but I see no improvement with this than the default atom search tool.

**Comment by antelle** [comment]
Just as a status update, I don't support this for now, because atom leaves much to be desired.

**Comment by antelle** [comment]
I moved to intellij idea, I mostly work with huge projects and I use its searching features a lot. I tried to make a better search in Atom, but it still didn't satisfy me in many aspects (indexing, performance, exclusions, etc...).
